details:
  namespace: student9-bookinfo-dev
  image: ghcr.io/kuraigi/itkmitl-bookinfo-details
  tag: uat
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8081
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: itkmitl.bookinfo.dev.opsta.net
  path: "/student9/details(/|$)(.*)"
  serviceType: ClusterIP